/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '用户名' at '17-6-12 下午1:33' with Gradle 2.13
 *
 * @author 用户名, @date 17-6-12 下午1:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
